global:
  scrape_interval: 15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    scheme: https
    metrics_path: /metrics
    scrape_interval: 15s
    basic_auth:
      username: "${PROM_USER}"
      password: "${PROM_PASS}"
    static_configs:
      - targets: ['gateway-production-1ee3.up.railway.app']

  - job_name: 'api'
    scheme: https
    metrics_path: /metrics
    scrape_interval: 15s
    basic_auth:
      username: "${PROM_USER}"
      password: "${PROM_PASS}"
    static_configs:
      - targets: ['api-production-f104.up.railway.app']

  - job_name: 'postgres'
    scheme: http
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'postgres-exporter-production-3068.up.railway.app:9187'

